services:
  db:
    image: mysql:8.0
    container_name: sb-strava-db
    environment:
      MYSQL_ROOT_PASSWORD: sbstravaapi_root_pw
      MYSQL_DATABASE: sb_strava_db
      MYSQL_USER: sb_strava
      MYSQL_PASSWORD: sb_strava
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "${MYSQL_USER}", "-p${MYSQL_PASSWORD}" ]
      interval: 5s
      timeout: 5s
      retries: 4
      start_period: 10s
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - app-network
  app:
    build: .
    container_name: sb-strava-app
    ports:
      - "9050:9050"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - app-network
    environment:
      DB_HOST: sb-strava-db
      STRAVA_CLIENT_ID: ${STRAVA_CLIENT_ID}
      STRAVA_CLIENT_SECRET: ${STRAVA_CLIENT_SECRET}
volumes:
  db_data:
networks:
  app-network:
    driver: bridge