CREATE TABLE lap (
         id int AUTO_INCREMENT,
         strava_lap_id BIGINT UNIQUE NOT NULL,
         activity_id INT NOT NULL,
         athlete_id INT NOT NULL,
         average_cadence FLOAT,
         average_speed FLOAT,
         distance FLOAT NOT NULL,
         elapsed_time INT NOT NULL,
         start_index INT,
         end_index INT,
         lap_index INT,
         max_speed FLOAT,
         moving_time INT NOT NULL,
         name VARCHAR(255) NOT NULL,
         pace_zone INT,
         split INT,
         start_date DATETIME NOT NULL,
         start_date_local DATETIME NOT NULL,
         total_elevation_gain FLOAT,
         CONSTRAINT pk_lap PRIMARY KEY (id)
);